
package ios.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-09T16:29:56.430+01:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "AccountInRedException", targetNamespace = "http://bankInterface/")
public class AccountInRedException_Exception extends Exception {
    
    private ios.client.AccountInRedException accountInRedException;

    public AccountInRedException_Exception() {
        super();
    }
    
    public AccountInRedException_Exception(String message) {
        super(message);
    }
    
    public AccountInRedException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public AccountInRedException_Exception(String message, ios.client.AccountInRedException accountInRedException) {
        super(message);
        this.accountInRedException = accountInRedException;
    }

    public AccountInRedException_Exception(String message, ios.client.AccountInRedException accountInRedException, Throwable cause) {
        super(message, cause);
        this.accountInRedException = accountInRedException;
    }

    public ios.client.AccountInRedException getFaultInfo() {
        return this.accountInRedException;
    }
}
