package ios.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-15T15:52:34.340+01:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "BankImplService", 
                  wsdlLocation = "http://localhost:8080/cxf-bank-server/cxf-bank-server?wsdl",
                  targetNamespace = "http://server.bank.ios/") 
public class BankImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.bank.ios/", "BankImplService");
    public final static QName BankImplPort = new QName("http://server.bank.ios/", "BankImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/cxf-bank-server/cxf-bank-server?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BankImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/cxf-bank-server/cxf-bank-server?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BankImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BankImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BankImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BankImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BankImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IBank
     */
    @WebEndpoint(name = "BankImplPort")
    public IBank getBankImplPort() {
        return super.getPort(BankImplPort, IBank.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IBank
     */
    @WebEndpoint(name = "BankImplPort")
    public IBank getBankImplPort(WebServiceFeature... features) {
        return super.getPort(BankImplPort, IBank.class, features);
    }

}
