
package ios.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-15T15:52:34.282+01:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "ClientAlreadyExistException", targetNamespace = "http://bankInterface/")
public class ClientAlreadyExistException_Exception extends Exception {
    
    private ios.client.ClientAlreadyExistException clientAlreadyExistException;

    public ClientAlreadyExistException_Exception() {
        super();
    }
    
    public ClientAlreadyExistException_Exception(String message) {
        super(message);
    }
    
    public ClientAlreadyExistException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ClientAlreadyExistException_Exception(String message, ios.client.ClientAlreadyExistException clientAlreadyExistException) {
        super(message);
        this.clientAlreadyExistException = clientAlreadyExistException;
    }

    public ClientAlreadyExistException_Exception(String message, ios.client.ClientAlreadyExistException clientAlreadyExistException, Throwable cause) {
        super(message, cause);
        this.clientAlreadyExistException = clientAlreadyExistException;
    }

    public ios.client.ClientAlreadyExistException getFaultInfo() {
        return this.clientAlreadyExistException;
    }
}
