
package ios.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-09T16:29:56.394+01:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "ClientDoNotExistException", targetNamespace = "http://bankInterface/")
public class ClientDoNotExistException_Exception extends Exception {
    
    private ios.client.ClientDoNotExistException clientDoNotExistException;

    public ClientDoNotExistException_Exception() {
        super();
    }
    
    public ClientDoNotExistException_Exception(String message) {
        super(message);
    }
    
    public ClientDoNotExistException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ClientDoNotExistException_Exception(String message, ios.client.ClientDoNotExistException clientDoNotExistException) {
        super(message);
        this.clientDoNotExistException = clientDoNotExistException;
    }

    public ClientDoNotExistException_Exception(String message, ios.client.ClientDoNotExistException clientDoNotExistException, Throwable cause) {
        super(message, cause);
        this.clientDoNotExistException = clientDoNotExistException;
    }

    public ios.client.ClientDoNotExistException getFaultInfo() {
        return this.clientDoNotExistException;
    }
}
