
package ios.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-11-09T16:29:56.403+01:00
 * Generated source version: 3.2.0
 */

@WebFault(name = "TypeOfAccountAlreadyExistForClientException", targetNamespace = "http://bankInterface/")
public class TypeOfAccountAlreadyExistForClientException_Exception extends Exception {
    
    private ios.client.TypeOfAccountAlreadyExistForClientException typeOfAccountAlreadyExistForClientException;

    public TypeOfAccountAlreadyExistForClientException_Exception() {
        super();
    }
    
    public TypeOfAccountAlreadyExistForClientException_Exception(String message) {
        super(message);
    }
    
    public TypeOfAccountAlreadyExistForClientException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TypeOfAccountAlreadyExistForClientException_Exception(String message, ios.client.TypeOfAccountAlreadyExistForClientException typeOfAccountAlreadyExistForClientException) {
        super(message);
        this.typeOfAccountAlreadyExistForClientException = typeOfAccountAlreadyExistForClientException;
    }

    public TypeOfAccountAlreadyExistForClientException_Exception(String message, ios.client.TypeOfAccountAlreadyExistForClientException typeOfAccountAlreadyExistForClientException, Throwable cause) {
        super(message, cause);
        this.typeOfAccountAlreadyExistForClientException = typeOfAccountAlreadyExistForClientException;
    }

    public ios.client.TypeOfAccountAlreadyExistForClientException getFaultInfo() {
        return this.typeOfAccountAlreadyExistForClientException;
    }
}
