package ios.foot;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-10-25T15:40:28.252+02:00
 * Generated source version: 3.2.0
 * 
 */
@WebService(targetNamespace = "http://footballpool.dataaccess.eu", name = "InfoSoapType")
@XmlSeeAlso({ObjectFactory.class})
public interface InfoSoapType {

    /**
     * Returns an array with all stadiums. The array contains the names, the city where the stadium can be found and the seat capacity
     */
    @WebMethod(operationName = "AllStadiumInfo")
    @RequestWrapper(localName = "AllStadiumInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllStadiumInfo")
    @ResponseWrapper(localName = "AllStadiumInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllStadiumInfoResponse")
    @WebResult(name = "AllStadiumInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftStadiumInfo allStadiumInfo();

    /**
     * Returns an array of all teams that compete with a link to the picture of their flag
     */
    @WebMethod(operationName = "Teams")
    @RequestWrapper(localName = "Teams", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.Teams")
    @ResponseWrapper(localName = "TeamsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TeamsResponse")
    @WebResult(name = "TeamsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftTeamInfo teams();

    /**
     * Returns an array with the names of all the coaches and the team information he/she is coaching
     */
    @WebMethod(operationName = "Coaches")
    @RequestWrapper(localName = "Coaches", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.Coaches")
    @ResponseWrapper(localName = "CoachesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.CoachesResponse")
    @WebResult(name = "CoachesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftCoaches coaches();

    /**
     * Number of games played so far
     */
    @WebMethod(operationName = "GamesPlayed")
    @RequestWrapper(localName = "GamesPlayed", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GamesPlayed")
    @ResponseWrapper(localName = "GamesPlayedResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GamesPlayedResponse")
    @WebResult(name = "GamesPlayedResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int gamesPlayed();

    /**
     * Returns information of the next game
     */
    @WebMethod(operationName = "NextGame")
    @RequestWrapper(localName = "NextGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.NextGame")
    @ResponseWrapper(localName = "NextGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.NextGameResponse")
    @WebResult(name = "NextGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TGameInfo nextGame();

    /**
     * Returns information (dates and number of games) about the tournament
     */
    @WebMethod(operationName = "TournamentInfo")
    @RequestWrapper(localName = "TournamentInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TournamentInfo")
    @ResponseWrapper(localName = "TournamentInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TournamentInfoResponse")
    @WebResult(name = "TournamentInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TTournamentInfo tournamentInfo();

    /**
     * Returns the number of games in the tournament
     */
    @WebMethod(operationName = "NumberOfGames")
    @RequestWrapper(localName = "NumberOfGames", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.NumberOfGames")
    @ResponseWrapper(localName = "NumberOfGamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.NumberOfGamesResponse")
    @WebResult(name = "NumberOfGamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int numberOfGames();

    /**
     * Returns an array of country names. The country is a property of a participant. You need the country ID to call PersonsPerCountry.
     */
    @WebMethod(operationName = "CountryNames")
    @RequestWrapper(localName = "CountryNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.CountryNames")
    @ResponseWrapper(localName = "CountryNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.CountryNamesResponse")
    @WebResult(name = "CountryNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftCountryInfo countryNames(
        @WebParam(name = "bWithCompetitors", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bWithCompetitors
    );

    /**
     * Returns an array of group id's and descriptions. Group is a poule collection of a knock out level
     */
    @WebMethod(operationName = "Groups")
    @RequestWrapper(localName = "Groups", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.Groups")
    @ResponseWrapper(localName = "GroupsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GroupsResponse")
    @WebResult(name = "GroupsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGroupInfo groups();

    /**
     * Returns an array with players that have a yellow card. Note: You can only sort on Name or Yellow cards, not on a combination.
     */
    @WebMethod(operationName = "AllPlayersWithYellowCards")
    @RequestWrapper(localName = "AllPlayersWithYellowCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithYellowCards")
    @ResponseWrapper(localName = "AllPlayersWithYellowCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithYellowCardsResponse")
    @WebResult(name = "AllPlayersWithYellowCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftPlayersWithCards allPlayersWithYellowCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByYellowCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByYellowCards
    );

    /**
     * Returns a combination of the total number of yellow and red cards given during this tournament (so far)
     */
    @WebMethod(operationName = "YellowAndRedCardsTotal")
    @RequestWrapper(localName = "YellowAndRedCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.YellowAndRedCardsTotal")
    @ResponseWrapper(localName = "YellowAndRedCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.YellowAndRedCardsTotalResponse")
    @WebResult(name = "YellowAndRedCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TCards yellowAndRedCardsTotal();

    /**
     * Returns an array with all given cards during the tournament
     */
    @WebMethod(operationName = "AllCards")
    @RequestWrapper(localName = "AllCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllCards")
    @ResponseWrapper(localName = "AllCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllCardsResponse")
    @WebResult(name = "AllCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftCardInfo allCards();

    /**
     * Returns the date of the first game
     */
    @WebMethod(operationName = "DateOfFirstGame")
    @RequestWrapper(localName = "DateOfFirstGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateOfFirstGame")
    @ResponseWrapper(localName = "DateOfFirstGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateOfFirstGameResponse")
    @WebResult(name = "DateOfFirstGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public javax.xml.datatype.XMLGregorianCalendar dateOfFirstGame();

    /**
     * Returns an array with the status codes for the games
     */
    @WebMethod(operationName = "GameResultCodes")
    @RequestWrapper(localName = "GameResultCodes", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GameResultCodes")
    @ResponseWrapper(localName = "GameResultCodesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GameResultCodesResponse")
    @WebResult(name = "GameResultCodesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGameResultCode gameResultCodes();

    /**
     * Returns an array with the id, name, country and flag reference of all players
     */
    @WebMethod(operationName = "AllPlayerNames")
    @RequestWrapper(localName = "AllPlayerNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayerNames")
    @ResponseWrapper(localName = "AllPlayerNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayerNamesResponse")
    @WebResult(name = "AllPlayerNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftPlayerNames allPlayerNames(
        @WebParam(name = "bSelected", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSelected
    );

    /**
     * Returns an array with the number of people signed up at that day
     */
    @WebMethod(operationName = "SignupsPerDate")
    @RequestWrapper(localName = "SignupsPerDate", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.SignupsPerDate")
    @ResponseWrapper(localName = "SignupsPerDateResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.SignupsPerDateResponse")
    @WebResult(name = "SignupsPerDateResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftSignupCount signupsPerDate();

    /**
     * Returns an array with the team of this competition with the number of times competed and the number of times won
     */
    @WebMethod(operationName = "TeamsCompeteList")
    @RequestWrapper(localName = "TeamsCompeteList", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TeamsCompeteList")
    @ResponseWrapper(localName = "TeamsCompeteListResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TeamsCompeteListResponse")
    @WebResult(name = "TeamsCompeteListResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftTeamCompete teamsCompeteList();

    /**
     * Returns an array with players that have a red or a yellow card. Note: You can only sort on Name, Yellow or Red cards, not on a combination.
     */
    @WebMethod(operationName = "AllPlayersWithYellowOrRedCards")
    @RequestWrapper(localName = "AllPlayersWithYellowOrRedCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithYellowOrRedCards")
    @ResponseWrapper(localName = "AllPlayersWithYellowOrRedCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithYellowOrRedCardsResponse")
    @WebResult(name = "AllPlayersWithYellowOrRedCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftPlayersWithCards allPlayersWithYellowOrRedCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByYellowCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByYellowCards,
        @WebParam(name = "bSortedByRedCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByRedCards
    );

    /**
     * Returns an array with players that have a red card. Note: You can only sort on Name or Red cards, not on a combination.
     */
    @WebMethod(operationName = "AllPlayersWithRedCards")
    @RequestWrapper(localName = "AllPlayersWithRedCards", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithRedCards")
    @ResponseWrapper(localName = "AllPlayersWithRedCardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllPlayersWithRedCardsResponse")
    @WebResult(name = "AllPlayersWithRedCardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftPlayersWithCards allPlayersWithRedCards(
        @WebParam(name = "bSortedByName", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByName,
        @WebParam(name = "bSortedByRedCards", targetNamespace = "http://footballpool.dataaccess.eu")
        boolean bSortedByRedCards
    );

    /**
     * List all the members of all groups/poules
     */
    @WebMethod(operationName = "AllGroupCompetitors")
    @RequestWrapper(localName = "AllGroupCompetitors", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGroupCompetitors")
    @ResponseWrapper(localName = "AllGroupCompetitorsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGroupCompetitorsResponse")
    @WebResult(name = "AllGroupCompetitorsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGroupsCompetitors allGroupCompetitors();

    /**
     * Returns an array of Games that are played in the passed city name
     */
    @WebMethod(operationName = "GamesPerCity")
    @RequestWrapper(localName = "GamesPerCity", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GamesPerCity")
    @ResponseWrapper(localName = "GamesPerCityResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GamesPerCityResponse")
    @WebResult(name = "GamesPerCityResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGameInfo gamesPerCity(
        @WebParam(name = "sCityName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCityName
    );

    /**
     * Returns the date of the last game (usually the finals...)
     */
    @WebMethod(operationName = "DateOfLastGame")
    @RequestWrapper(localName = "DateOfLastGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateOfLastGame")
    @ResponseWrapper(localName = "DateOfLastGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateOfLastGameResponse")
    @WebResult(name = "DateOfLastGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public javax.xml.datatype.XMLGregorianCalendar dateOfLastGame();

    /**
     * Returns the information about a particular game
     */
    @WebMethod(operationName = "GameInfo")
    @RequestWrapper(localName = "GameInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GameInfo")
    @ResponseWrapper(localName = "GameInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GameInfoResponse")
    @WebResult(name = "GameInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TGameInfo gameInfo(
        @WebParam(name = "iGameId", targetNamespace = "http://footballpool.dataaccess.eu")
        int iGameId
    );

    /**
     * Returns an array with the names of all defenders. If you pass a country name the result will be filtered on that country, so you only get the defenders listed for the specified country
     */
    @WebMethod(operationName = "AllDefenders")
    @RequestWrapper(localName = "AllDefenders", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllDefenders")
    @ResponseWrapper(localName = "AllDefendersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllDefendersResponse")
    @WebResult(name = "AllDefendersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString allDefenders(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    /**
     * Returns the number of groups in the tournament
     */
    @WebMethod(operationName = "GroupCount")
    @RequestWrapper(localName = "GroupCount", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GroupCount")
    @ResponseWrapper(localName = "GroupCountResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GroupCountResponse")
    @WebResult(name = "GroupCountResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int groupCount();

    /**
     * Returns a number on how many times the given team competed at a worldcup football
     */
    @WebMethod(operationName = "PlayedAtWorldCup")
    @RequestWrapper(localName = "PlayedAtWorldCup", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.PlayedAtWorldCup")
    @ResponseWrapper(localName = "PlayedAtWorldCupResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.PlayedAtWorldCupResponse")
    @WebResult(name = "PlayedAtWorldCupResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int playedAtWorldCup(
        @WebParam(name = "sTeamName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sTeamName
    );

    /**
     * List all the members of a group/poule
     */
    @WebMethod(operationName = "GroupCompetitors")
    @RequestWrapper(localName = "GroupCompetitors", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GroupCompetitors")
    @ResponseWrapper(localName = "GroupCompetitorsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GroupCompetitorsResponse")
    @WebResult(name = "GroupCompetitorsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftTeamInfo groupCompetitors(
        @WebParam(name = "sPoule", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sPoule
    );

    /**
     * Returns an array with all the city names where games are played
     */
    @WebMethod(operationName = "Cities")
    @RequestWrapper(localName = "Cities", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.Cities")
    @ResponseWrapper(localName = "CitiesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.CitiesResponse")
    @WebResult(name = "CitiesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString cities();

    /**
     * Returns an array with the names of all forwards. If you pass a country name the result will be filtered on that country, so you only get the forwards listed for the specified country
     */
    @WebMethod(operationName = "AllForwards")
    @RequestWrapper(localName = "AllForwards", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllForwards")
    @ResponseWrapper(localName = "AllForwardsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllForwardsResponse")
    @WebResult(name = "AllForwardsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString allForwards(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    /**
     * Returns an array of scored goals. If the game id is passed only for that game. You can get the game ID's via the method AllGames
     */
    @WebMethod(operationName = "GoalsScored")
    @RequestWrapper(localName = "GoalsScored", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GoalsScored")
    @ResponseWrapper(localName = "GoalsScoredResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.GoalsScoredResponse")
    @WebResult(name = "GoalsScoredResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGoal goalsScored(
        @WebParam(name = "iGameId", targetNamespace = "http://footballpool.dataaccess.eu")
        int iGameId
    );

    /**
     * Returns an array of stadium names where the games are played
     */
    @WebMethod(operationName = "StadiumNames")
    @RequestWrapper(localName = "StadiumNames", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumNames")
    @ResponseWrapper(localName = "StadiumNamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumNamesResponse")
    @WebResult(name = "StadiumNamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString stadiumNames();

    /**
     * Returns an array with the top N selected goal scorers and how often they are selected. Pass 0 as TopN and you get them all.
     */
    @WebMethod(operationName = "TopSelectedGoalScorers")
    @RequestWrapper(localName = "TopSelectedGoalScorers", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TopSelectedGoalScorers")
    @ResponseWrapper(localName = "TopSelectedGoalScorersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TopSelectedGoalScorersResponse")
    @WebResult(name = "TopSelectedGoalScorersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftTopSelectedGoalScorer topSelectedGoalScorers(
        @WebParam(name = "iTopN", targetNamespace = "http://footballpool.dataaccess.eu")
        int iTopN
    );

    /**
     * Returns an array with the names of all midfields. If you pass a country name the result will be filtered on that country, so you only get the midfields listed for the specified country
     */
    @WebMethod(operationName = "AllMidFields")
    @RequestWrapper(localName = "AllMidFields", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllMidFields")
    @ResponseWrapper(localName = "AllMidFieldsResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllMidFieldsResponse")
    @WebResult(name = "AllMidFieldsResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString allMidFields(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );

    /**
     * Returns the date of the last group game will be played. After this date the quarter finals are played.
     */
    @WebMethod(operationName = "DateLastGroupGame")
    @RequestWrapper(localName = "DateLastGroupGame", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateLastGroupGame")
    @ResponseWrapper(localName = "DateLastGroupGameResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.DateLastGroupGameResponse")
    @WebResult(name = "DateLastGroupGameResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public javax.xml.datatype.XMLGregorianCalendar dateLastGroupGame();

    /**
     * Returns a URL that can be used to show a small map of the stadium
     */
    @WebMethod(operationName = "StadiumURL")
    @RequestWrapper(localName = "StadiumURL", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumURL")
    @ResponseWrapper(localName = "StadiumURLResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumURLResponse")
    @WebResult(name = "StadiumURLResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public java.lang.String stadiumURL(
        @WebParam(name = "sStadiumName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sStadiumName
    );

    /**
     * Returns the total number of yellow cards given during this tournament (so far)
     */
    @WebMethod(operationName = "YellowCardsTotal")
    @RequestWrapper(localName = "YellowCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.YellowCardsTotal")
    @ResponseWrapper(localName = "YellowCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.YellowCardsTotalResponse")
    @WebResult(name = "YellowCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int yellowCardsTotal();

    /**
     * Returns an array of games information
     */
    @WebMethod(operationName = "AllGames")
    @RequestWrapper(localName = "AllGames", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGames")
    @ResponseWrapper(localName = "AllGamesResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGamesResponse")
    @WebResult(name = "AllGamesResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftGameInfo allGames();

    /**
     * Returns all team info from a passed team; name, flag, playernames (by role), trainer
     */
    @WebMethod(operationName = "FullTeamInfo")
    @RequestWrapper(localName = "FullTeamInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.FullTeamInfo")
    @ResponseWrapper(localName = "FullTeamInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.FullTeamInfoResponse")
    @WebResult(name = "FullTeamInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TFullTeamInfo fullTeamInfo(
        @WebParam(name = "sTeamName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sTeamName
    );

    /**
     * Returns an array with the top N goal scorers and their current score. Pass 0 as TopN and you get them all.
     */
    @WebMethod(operationName = "TopGoalScorers")
    @RequestWrapper(localName = "TopGoalScorers", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TopGoalScorers")
    @ResponseWrapper(localName = "TopGoalScorersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.TopGoalScorersResponse")
    @WebResult(name = "TopGoalScorersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOftTopGoalScorer topGoalScorers(
        @WebParam(name = "iTopN", targetNamespace = "http://footballpool.dataaccess.eu")
        int iTopN
    );

    /**
     * Returns the information we keep about a particular stadium, Pass the name of the stadium
     */
    @WebMethod(operationName = "StadiumInfo")
    @RequestWrapper(localName = "StadiumInfo", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumInfo")
    @ResponseWrapper(localName = "StadiumInfoResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.StadiumInfoResponse")
    @WebResult(name = "StadiumInfoResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.TStadiumInfo stadiumInfo(
        @WebParam(name = "sStadiumName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sStadiumName
    );

    /**
     * Returns the total number of red cards given during this tournament (so far)
     */
    @WebMethod(operationName = "RedCardsTotal")
    @RequestWrapper(localName = "RedCardsTotal", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.RedCardsTotal")
    @ResponseWrapper(localName = "RedCardsTotalResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.RedCardsTotalResponse")
    @WebResult(name = "RedCardsTotalResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public int redCardsTotal();

    /**
     * Returns an array with the names of all goalkeepers. If you pass a country name the result will be filtered on that country, so you only get the goalkeepers listed for the specified country
     */
    @WebMethod(operationName = "AllGoalKeepers")
    @RequestWrapper(localName = "AllGoalKeepers", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGoalKeepers")
    @ResponseWrapper(localName = "AllGoalKeepersResponse", targetNamespace = "http://footballpool.dataaccess.eu", className = "ios.foot.AllGoalKeepersResponse")
    @WebResult(name = "AllGoalKeepersResult", targetNamespace = "http://footballpool.dataaccess.eu")
    public ios.foot.ArrayOfString allGoalKeepers(
        @WebParam(name = "sCountryName", targetNamespace = "http://footballpool.dataaccess.eu")
        java.lang.String sCountryName
    );
}
